##################################################################################
#####                                TODO                                    #####
##################################################################################
Activity:
  path: webservice/activity/
  properties:
    athlete:
      type: Member
      required: true
    name:
      type: String
      required: true
    distance:
      type: double
      required: true
    moving_time:
      type: int
      required: true
    elapsed_time:
      type: int
      required: true
    total_elevation_gain:
      type: double
      required: true
    type:
      type: String

ActivitySummary:
    path: webservice/activity_summary/
    properties:
      total_distance:
        non_final: true
        required: true
        type: double
      total_moving_time:
        non_final: true
        required: true
        type: int
      total_elapsed_time:
        non_final: true
        required: true
        type: int
      total_elevatiion_gain:
        non_final: true
        required: true
        type: double

Member:
  path: webservice/member/
  properties:
    id:
      non_final: true
      type: String
    firstname:
      non_final: true
      required: true
      type: String
    lastname:
      non_final: true
      required: true
      type: String
    isAdmin:
      non_final: true
      type: bool

MemberStats:
  path: webservice/member_stats/
  properties:
    id:
      non_final: true
      type: String
    firstname:
      non_final: true
      required: true
      type: String
    lastname:
      non_final: true
      required: true
      type: String
    total_distance:
      non_final: true
      required: true
      type: double
    total_moving_time:
      non_final: true
      required: true
      type: int
    total_elapsed_time:
      non_final: true
      required: true
      type: int
    total_elevatiion_gain:
      non_final: true
      required: true
      type: double

Club:
  path: webservice/club/
  properties:
    id:
      type: int
    name:
      type: String
    profile_medium:
      type: String
    profile:
      type: String
    cover_photo:
      type: String
    cover_photo_small:
      type: String
    sport_type:
      type: String
    city:
      type: String
    state:
      type: String
    country:
      type: String
    private:
      type: bool
    member_count:
      type: int
    featured:
      type: bool
    verified:
      type: bool
    url:
      type: String
    membership:
      type: String
    admin: 
      type: bool
    owner: 
      type: bool
    description:
      type: String
    club_type:
      type: String
    post_count:
      type: int
    owner_id:
      type: int
    following_count:
      type: int
