##################################################################################
#####                                TODO                                    #####
##################################################################################
Activity:
  path: webservice/activity/
  properties:
    athlete:
      type: Member
    name:
      type: String
    distance:
      type: double
    moving_time:
      type: double
    elapsed_time:
      type: double
    total_elevation_gain:
      type: double
    type:
      type: String

Member:
  path: webservice/member/
  properties:
    firstname:
      type: String
    lastname:
      type: String

Club:
  path: webservice/club/
  properties:
    id:
      type: int
    name:
      type: String
    profile_medium:
      type: String
    profile:
      type: String
    cover_photo:
      type: String
    cover_photo_small:
      type: String
    sport_type:
      type: String
    city:
      type: String
    state:
      type: String
    country:
      type: String
    private:
      type: bool
    member_count:
      type: int
    featured:
      type: bool
    verified:
      type: bool
    url:
      type: String
    membership:
      type: String
    admin: 
      type: bool
    owner: 
      type: bool
    description:
      type: String
    club_type:
      type: String
    post_count:
      type: int
    owner_id:
      type: int
    following_count:
      type: int
