##################################################################################
#####                                TODO                                    #####
##################################################################################
Member:
  path: webservice/member/
  properties:
    firstname:
      type: String
    lastname:
      type: String
